spring.application.name=moonshop
server.port=8080
spring.config.import=optional:file:.env[.properties]

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Redis cache-aside
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.connect-timeout=${REDIS_CONNECT_TIMEOUT}
spring.data.redis.timeout=${REDIS_TIMEOUT}
spring.data.redis.repositories.enabled=false

#JWT
jwt.secret=${JWT_SECRET}
jwt.access.expiration_time=${JWT_ACCESS_EXPIRATION_TIME}
jwt.refresh.expiration_time=${JWT_REFRESH_EXPIRATION_TIME}

#Swagger
springdoc.api-docs.enabled=${SPRINGDOC_ENABLED:true}
springdoc.swagger-ui.enabled=${SPRINGDOC_ENABLED:true}
springdoc.packagesToScan=quynh.ecommerce.moonshop
springdoc.pathsToMatch=/**

#Security Endpoint
security.public-endpoints=/api/auth/register,/api/auth/login,/api/auth/refresh-token,/api/products/**,/api/categories
security.user-endpoints=/api/cart/**,/api/orders/**,/api/chat/**
security.admin-endpoints=/api/admin/**
security.swagger-endpoints=/swagger-ui/**,/v3/api-docs/**,/swagger-ui.html
security.cors.allowed-origins=${SECURITY_CORS_ALLOWED_ORIGINS}

#Info Admin
app.admin.username=${APP_ADMIN_USERNAME}
app.admin.email=${APP_ADMIN_EMAIL}
app.admin.password=${APP_ADMIN_PASSWORD}
app.admin.firstName=${APP_ADMIN_FIRSTNAME}
app.admin.lastName=${APP_ADMIN_LASTNAME}

#RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

rabbitmq.exchange.name=${RABBITMQ_EXCHANGE_NAME}
rabbitmq.queue.name=${RABBITMQ_QUEUE_NAME}
rabbitmq.routing.key=${RABBITMQ_ROUTING_KEY}
rabbitmq.queue.json.name=${RABBITMQ_QUEUE_JSON_NAME}
rabbitmq.routing.json.key=${RABBITMQ_ROUTING_JSON_KEY}

#Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
